package visual.driver;

import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class EditDriver extends javax.swing.JFrame {

    /**
     * Creates new form EditDriver
     */
    public EditDriver() {
        initComponents();
        this.dispose();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RouteNUMBER = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BusDriverEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DriverPhoneNumEdit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DriverAddressEdit = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        EmpNumEdit = new javax.swing.JTextField();
        jComboBoxDepED = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Busnumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        RouteId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Save = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 236, 243));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RouteNUMBER.setBorder(null);
        RouteNUMBER.setOpaque(false);
        RouteNUMBER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RouteNUMBERKeyTyped(evt);
            }
        });
        jPanel1.add(RouteNUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 30));

        jLabel2.setText("Route number ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        BusDriverEdit.setBorder(null);
        BusDriverEdit.setOpaque(false);
        jPanel1.add(BusDriverEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 205, 30));

        jLabel4.setText("Phone number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        DriverPhoneNumEdit.setBorder(null);
        DriverPhoneNumEdit.setOpaque(false);
        DriverPhoneNumEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DriverPhoneNumEditKeyTyped(evt);
            }
        });
        jPanel1.add(DriverPhoneNumEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 90, 30));

        jLabel9.setText("Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        DriverAddressEdit.setColumns(20);
        DriverAddressEdit.setRows(5);
        jScrollPane1.setViewportView(DriverAddressEdit);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel5.setText("Employee number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, -1));

        EmpNumEdit.setBorder(null);
        EmpNumEdit.setOpaque(false);
        EmpNumEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmpNumEditKeyTyped(evt);
            }
        });
        jPanel1.add(EmpNumEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 30));

        jComboBoxDepED.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM1", "PM2", "PM3", "PM4" }));
        jPanel1.add(jComboBoxDepED, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 58, -1));

        jLabel10.setText("Route id");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel11.setText("Bus number");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        Busnumber.setBorder(null);
        Busnumber.setOpaque(false);
        Busnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusnumberKeyTyped(evt);
            }
        });
        jPanel1.add(Busnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 30));

        jLabel12.setText("Route departure");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        RouteId.setBorder(null);
        RouteId.setOpaque(false);
        RouteId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RouteIdKeyTyped(evt);
            }
        });
        jPanel1.add(RouteId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 90, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 15, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anna Karenina\\Documents\\NetBeansProjects\\Visual\\Images\\Dashboard\\edit driver.png")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 205, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 70, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 90, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 90, 10));

        Save.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anna Karenina\\Documents\\NetBeansProjects\\Visual\\Images\\Button\\Save.png")); // NOI18N
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 710));

        pack();
    }// </editor-fold>                        

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {                                     
        setState(JFrame.ICONIFIED);
    }                                    

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {                                     
        this.dispose();
    }                                    
public Connection getConnection(){
        Connection con;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/coba", "root", "");
            return con;
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return null;
    }
    private void EmpNumEditKeyTyped(java.awt.event.KeyEvent evt) {                                    
        if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
       }
    }                                   

    private void DriverPhoneNumEditKeyTyped(java.awt.event.KeyEvent evt) {                                            
        if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
       }
    }                                           

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {                                  
        if(EmpNumEdit.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Insert employee number"); 
        } else if(BusDriverEdit.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Insert name");
        } else if(Busnumber.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Insert bus number");
        } else if(RouteNUMBER.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Insert route number");
        } else if(RouteId.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Insert route id");
        } else if(DriverAddressEdit.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Insert address");
        } else if(DriverPhoneNumEdit.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Insert phone number");
        } else {
        PreparedStatement ps;
        Connection c = getConnection();
        String sql = "UPDATE bus_driver SET Route_departure=?,Route_number=?,Employee_number=?,Bus_number=?,Bus_drivername=?,Phone_number=?,Address=? WHERE Route_id_driver=?";
        try{
            ps = c.prepareStatement(sql);
            ps.setString(1, (String) jComboBoxDepED.getSelectedItem());
            ps.setString(2, RouteNUMBER.getText());
            ps.setString(3, EmpNumEdit.getText());
            ps.setString(4, Busnumber.getText());
            ps.setString(5, BusDriverEdit.getText());
            ps.setString(6, DriverPhoneNumEdit.getText());
            ps.setString(7, DriverAddressEdit.getText());
            ps.setString(8, RouteId.getText());
            
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Edit success");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong");
        }
        this.dispose();
        }
    }                                 

    private void BusnumberKeyTyped(java.awt.event.KeyEvent evt) {                                   
        if(Character.isLowerCase(evt.getKeyChar())){
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }                                  

    private void RouteNUMBERKeyTyped(java.awt.event.KeyEvent evt) {                                     
        if(Character.isLowerCase(evt.getKeyChar())){
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }                                    

    private void RouteIdKeyTyped(java.awt.event.KeyEvent evt) {                                 
        if(Character.isLowerCase(evt.getKeyChar())){
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    public javax.swing.JTextField BusDriverEdit;
    public javax.swing.JTextField Busnumber;
    public javax.swing.JTextArea DriverAddressEdit;
    public javax.swing.JTextField DriverPhoneNumEdit;
    public javax.swing.JTextField EmpNumEdit;
    public javax.swing.JTextField RouteId;
    public javax.swing.JTextField RouteNUMBER;
    private javax.swing.JLabel Save;
    public javax.swing.JComboBox<String> jComboBoxDepED;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration                   
}
